app/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from screener import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('screener/', include('screener.urls')),
    path('get_data_status', views.get_data_status, name='get_data_status')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/screener/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from . import views, converters
from django.conf import settings
from django.conf.urls.static import static

register_converter(converters.FloatUrlParameterConverter, 'float')

app_name = 'screener'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:symbol>-<int:tf>', views.currency_chart, name='currency_chart'),
    path('status', views.index_status, name='index_status')
]

app/screener/models.py
from django.db import models

# Create your models here.

app/screener/views.py
from django.shortcuts import render
from django.http import JsonResponse
from datetime import datetime, timedelta
import ccxt
import pandas as pd

from screener.services import collect_all_data_for_screener

from screener.database import get_status, get_all_currency

from screener.exchange import get_last_prices, get_all_min_step, get_candles_by_date

from screener.charts import chart_with_flat


currency_list = get_all_currency()

def index(request):

    try:
        print('Good')
        data = collect_all_data_for_screener()
        list_tf = [5,15,30,60]

        return render(request, 'screener/index.html', {'data':data, 'list_tf':list_tf})
    except Exception as e:
        print(e)

from screener.services import get_currency_chart_with_impulse

def currency_chart(request, symbol, tf):
    print(symbol, tf)
    chart = get_currency_chart_with_impulse(symbol,tf, currency_list['Bybit']['Future'][symbol]['min_step'])
    return render(request, 'screener/currency_chart.html', {'chart':chart})




def index_status(request):
    return render(request, 'screener/status_check.html')

def get_data_status(request):
    
    status_db = get_status()

    status_list = []

    for status in status_db:
        my_list = list(status)
        my_list[3] = my_list[3].strftime("%d/%m/%Y, %H:%M:%S")
        status_list.append(my_list)
    
    return JsonResponse({'status_list':status_list})

app/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static "css/styles.css" %}" />
    <script src="https://yastatic.net/jquery/3.3.1/jquery.min.js"></script>
    <title>{% block title%}{% endblock %}</title>
  </head>
  <body style="--tw-bg-opacity: 1; background-color: rgb(20 20 20 / var(--tw-bg-opacity));color:rgb(224, 224, 224);">
    <style>
      .nav-link {
        color:rgb(224, 224, 224);
        font-weight: bolder;
        padding-top: 10px;
        font-size: 30px;
      }
    </style>
    <div class="container">
      <ul style="height: 60px" class="nav nav-pills nav-fill nav-dark bg-dark">
        <li class="nav-item">
          <a
            class="nav-link"
            aria-current="page"
            href="{% url 'screener:index'%}"
            >Impulses</a
          >
        </li>
      </ul>
    </div>

    <div class="container">{% block content %} {% endblock%}</div>
  </body>
</html>

app/templates/screener/all_flats.html
{% extends "base.html" %}
{% block title %}
    Accumilations
{% endblock title %}
{% block content %}
{% load static %}

    <h1 style ='text-align:center'>Bybit Futures</h1>
     <div class="table-responsive">
        <table id="tblFlats"
            class="table table-dark table-hover table-bordered" style="color:rgb(224, 224, 224);">
            <thead class="table-dark">
                <tr>
                    <th style="text-align:center;color:rgb(224, 224, 224);" width="20%">
                        Name</th>
                    <th style="text-align:center;color:rgb(224, 224, 224);">TF</th>
                    <th style="text-align:center;color:rgb(224, 224, 224);">Count Retest</th>
                    <th style="text-align:center;color:rgb(224, 224, 224);">Last Retest</th>
                    <th style="text-align:center;color:rgb(224, 224, 224);">Left Pips</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div> 
    
            
    <script>
        $(document).ready(function(){
            setInterval(function(){
                $.ajax({
                    type: 'GET',
                    url : "/get_data_flat",
                    success: function(response) {
                        
                        $('#tblFlats tbody').empty();
    
                        try{
                            var tr;
                            var image;
                            $.each(response.flats, function (index, flat){
                                tr = $(`<tr style="background-color: rgba(0, 0, 0, 0.5);">`);

                                var imagePath = `/static/images/${flat[1]}.png`; // Предполагается, что имя изображения соответствует значению flat[1]

                                if (flat[3] == 1)
                                {
                                    tr.append(`<td><img src="${imagePath}" alt="${flat[1]}" width="50" height="50">
                                    <a style="color:rgb(126, 205, 135);" href="/screener/flats/${flat[0]}">
                                        ${flat[1]}
                                    </a></td>`);
                                } 
                                else
                                {
                                    tr.append(`<td><img src="${imagePath}" alt="${flat[1]}" width="50" height="50">
                                    <a style="color:rgb(126, 205, 135);" href="/screener/flats/${flat[0]}">
                                        ${flat[1]}
                                    </a></td>`);
                                }
                                
                                tr.append(`<td>${flat[2]}</td>`);
                                tr.append(`<td>${flat[4]}</td>`);
                                tr.append(`<td>${flat[5]} min</td>`);
                                tr.append(`<td>${flat[6]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblFlats').append(tr); 
                            });

                        }
                        catch(err){
                            console.log(err);
                        }
                    },
                    error : function(response){
                        
                    }
                });
            },3000);
        })
    </script>
{% endblock content %}

app/templates/screener/big_orders.html
{% extends "base.html" %}
{% block title %}
    Order Book
{% endblock title %}
{% block content %}
    
    <h1 style ='text-align:center'>Levels With Order</h1>
    <div class="table-responsive">
    <table id="tblOrderLevel"
        class="table mt-2 table-bordered table-striped table-hover table-responsive">
        <thead class="table-dark">
            <tr>
                <th style="text-align:center;" width="10%">Name</th>
                <th style="text-align:center">Price Level</th>
                <th style="text-align:center">Time Live</th>
                <th style="text-align:center">Left Pips</th>
                <th style="text-align:center">Price Order</th>
                <th style="text-align:center">Pow</th>
                <th style="text-align:center">Time Live</th>
                <th style="text-align:center">Left Pips Order</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    </div>
    <h1 style ='text-align:center'>Big Orders Bybit</h1>
    <div class='row'>
        <div class='col-6'>
            <h1 style ='text-align:center'>Orders Spot</h1>
            <div class="table-responsive">
            <table id="tblOrders_SBybit"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th style="text-align:center;" width="10%">Name</th>
                        <th style="text-align:center;">Type</th>
                        <th style="text-align:center">Price</th>
                        <th style="text-align:center">Quantity</th>
                        <th style="text-align:center">Pow</th>
                        <th style="text-align:center">Time live</th>
                        <th style="text-align:center">Left Pips</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
        <div class='col-6'>
            <h1 style ='text-align:center'>Orders Futures</h1>
            <div class="table-responsive">
            <table id="tblOrders_FBybit"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th style="text-align:center;" width="10%">Name</th>
                        <th style="text-align:center;">Type</th>
                        <th style="text-align:center">Price</th>
                        <th style="text-align:center">Quantity</th>
                        <th style="text-align:center">Pow</th>
                        <th style="text-align:center">Time live</th>
                        <th style="text-align:center">Left Pips</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <h1 style ='text-align:center'>Big Orders Binance</h1>
    <div class='row'>
        <div class='col-6'>
            <h1 style ='text-align:center'>Orders Spot</h1>
            <div class="table-responsive">
            <table id="tblOrders_SBinance"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th style="text-align:center;" width="10%">Name</th>
                        <th style="text-align:center;">Type</th>
                        <th style="text-align:center">Price</th>
                        <th style="text-align:center">Quantity</th>
                        <th style="text-align:center">Pow</th>
                        <th style="text-align:center">Time live</th>
                        <th style="text-align:center">Left Pips</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
        <div class='col-6'>
            <h1 style ='text-align:center'>Orders Futures</h1>
            <div class="table-responsive">
            <table id="tblOrders_FBinance"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th style="text-align:center;" width="10%">Name</th>
                        <th style="text-align:center;">Type</th>
                        <th style="text-align:center">Price</th>
                        <th style="text-align:center">Quantity</th>
                        <th style="text-align:center">Pow</th>
                        <th style="text-align:center">Time live</th>
                        <th style="text-align:center">Left Pips</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    
            
    <script>
        $(document).ready(function(){
            setInterval(function(){
                $.ajax({
                    type: 'GET',
                    url : "/get_data_order_book",
                    success: function(response) {
                        
                        $('#tblOrders_SBybit tbody').empty();
                        $('#tblOrders_FBybit tbody').empty();
                        $('#tblOrders_SBinance tbody').empty();
                        $('#tblOrders_FBinance tbody').empty();
                        $('#tblOrderLevel tbody').empty();
    
                        try{
                            var tr;
                            
                            $.each(response.orders_f_by, function (index, order){

                                if (order[1] == 'bids')
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td>${order[0]}</td>`);
                                tr.append(`<td>${order[1]}</td>`);
                                tr.append(`<td>${order[2]}</td>`);
                                tr.append(`<td>${order[3]}</td>`);
                                tr.append(`<td>${order[4]}</td>`);
                                tr.append(`<td>${order[5]} minute</td>`);
                                tr.append(`<td>${order[6]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblOrders_FBybit').append(tr); 
                            });

                            $.each(response.orders_s_by, function (index, order){
                                if (order[1] == 'bids')
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td>${order[0]}</td>`);
                                tr.append(`<td>${order[1]}</td>`);
                                tr.append(`<td>${order[2]}</td>`);
                                tr.append(`<td>${order[3]}</td>`);
                                tr.append(`<td>${order[4]}</td>`);
                                tr.append(`<td>${order[5]} minute</td>`);
                                tr.append(`<td>${order[6]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblOrders_SBybit').append(tr); 
                            });

                            $.each(response.orders_f_bi, function (index, order){

                                if (order[1] == 'bids')
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td>${order[0]}</td>`);
                                tr.append(`<td>${order[1]}</td>`);
                                tr.append(`<td>${order[2]}</td>`);
                                tr.append(`<td>${order[3]}</td>`);
                                tr.append(`<td>${order[4]}</td>`);
                                tr.append(`<td>${order[5]} minute</td>`);
                                tr.append(`<td>${order[6]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblOrders_FBinance').append(tr); 
                            });

                            $.each(response.orders_s_bi, function (index, order){
                                if (order[1] == 'bids')
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td>${order[0]}</td>`);
                                tr.append(`<td>${order[1]}</td>`);
                                tr.append(`<td>${order[2]}</td>`);
                                tr.append(`<td>${order[3]}</td>`);
                                tr.append(`<td>${order[4]}</td>`);
                                tr.append(`<td>${order[5]} minute</td>`);
                                tr.append(`<td>${order[6]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblOrders_SBinance').append(tr); 
                            });

                            $.each(response.close_levels, function (index, level){
                                if (level[0] == 2)
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td>${level[1]}</td>`);
                                tr.append(`<td>${level[2]}</td>`);
                                tr.append(`<td>${level[3]} min</td>`);
                                tr.append(`<td>${level[4]} %</td>`);
                                tr.append(`<td>${level[5]}</td>`);
                                tr.append(`<td>${level[6]}</td>`);
                                tr.append(`<td>${level[7]} min</td>`);
                                tr.append(`<td>${level[8]} %</td>`);
                                tr.append(`</tr>`)
                                $('#tblOrderLevel').append(tr); 
                            });
                            


                        }
                        catch(err){
                            console.log(err);
                        }
                    },
                    error : function(response){
                        
                    }
                });
            },3000);
        })
    </script>
{% endblock content %}

app/templates/screener/close_levels.html
{% extends "base.html" %}
{% block title %}
    Levels
{% endblock title %}
{% block content %}
    
    <h1 style ='text-align:center'>Close Levels Futures</h1>
    <div class="table-responsive">
        <table id="tblCloseLevels_S"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
            <thead class="table-dark">
                <tr>
                    <th style='text-align:center' width="10%">Symbol</th>
                    <th style="text-align:center">Level One</th>
                    <th style="text-align:center">Level Two</th>
                    <th style="text-align:center">Price Three</th>
                    <th style="text-align:center">Left pips</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
            
    <script>
        $(document).ready(function(){
            setInterval(function(){
                $.ajax({
                    type: 'GET',
                    url : "/get_data",
                    success: function(response) {
                        
                        $('#tblCloseLevels_S tbody').empty();
    
                        try{
                            var tr;
                            $.each(response.close_levels, function (index, level){
                                console.log(level)
                                if (level[1] == 2)
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td><a href="/screener/close_level/${level[0]}/${level[2]}">
                                    ${level[0]}
                                </a></td>`);
                                tr.append(`<td>${level[2]}</td>`);
                                tr.append(`<td>${level[3]}</td>`);
                                tr.append(`<td>${level[4]}</td>`);
                                tr.append(`<td>${level[5]} %</td>`);
                                
                                
                                tr.append(`</tr>`)
                                $('#tblCloseLevels_S').append(tr); 
                            });
                        }
                        catch(err){
                            console.log(err);
                        }
                    },
                    error : function(response){
                        
                    }
                });
            },3000);
        })
    </script>
{% endblock content %}

app/templates/screener/currency_chart.html
{% extends "base.html" %}
{% block title %}
    Chart
{% endblock title %}
{% block content %}
    <div class='row' style='height:800px;'>
        {{ chart|safe }}
    </div>
{% endblock content %}

app/templates/screener/current_cubes.html
{% extends "base.html" %}
{% block title %}
    Chart
{% endblock title %}
{% block content %}
    <h1 style='text-align:center'>{{name}}</h1>
    {{ chart|safe }}
{% endblock content %}

app/templates/screener/current_flat.html
{% extends "base.html" %}
{% block title %}
    {{name}}
{% endblock title %}
{% block content %}
    <h1 style='text-align:center'>{{name}}</h1>
    <div class='row' style='height:800px;'>
        {{ chart|safe }}
    </div>
    
{% endblock content %}

app/templates/screener/index.html
{% extends "base.html" %}
{% block title %}
    Impulse Screener
{% endblock title %}
{% block content %}
    <h1 style ='text-align:center'>Bybit Futures</h1>
    <table class="table table-dark  table-bordered">
        <thead class="table-dark">
            <tr>
                <th rowspan="2">Name</th>
                {% comment %} <th colspan="2">1 min Orders</th> {% endcomment %}
                {% for tf in list_tf %}<th colspan="3">{{ tf }} min</th>{% endfor %}
            </tr>
            <tr>
                {% comment %} <th>Order Bid</th>
                <th>Order Ask</th> {% endcomment %}
                {% for el in list_tf %}
                    <th>Have Impulse</th>
                    <th>Have Levels</th>
                    <th>Have Order</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% load color_filter %}
            {% for key, value in data.items %}
                <tr>
                    <td>
                        {% comment %} <a style="color:black; text-align: center" href="{% url "screener:orders_chart" key %}">
                            <p style='font-size:18px'>{{ key }}</p>
                        </a> {% endcomment %}
                        <p style='font-size:18px'>
                            {{ key }}
                        </p>
                    </td>
                    {% comment %} <td class="{{ value.orders.bids.period|color_filter_bids }}">
                        <p style="{{ value.orders.bids.period|color_filter_bids_asks_text }}; text-align: center">{{ value.orders.bids.period }} - {{ value.orders.bids.pow }}</p>
                    </td>
                    <td class="{{ value.orders.asks.period|color_filter_asks }}">
                        <p style="{{ value.orders.asks.period|color_filter_bids_asks_text }}; text-align: center">{{ value.orders.asks.period }} - {{ value.orders.asks.pow }}</p>
                    </td> {% endcomment %}
                    {% for keyTF, value in value.tf.items %}
                        {% if value.text == "График" %}
                            <td class="{{ value.type|color_filter_impulse }}">
                                <a style="{{ value.type|color_filter_impulse_text }};
                                          text-align: center"
                                   href="{% url "screener:currency_chart" key keyTF %}">
                                    <p>{{ value.text }}</p>
                                </a>
                            </td>
                            <td class="{{ value|color_filter_count_level }}">
                                <p style="{{ value|color_filter_count_level_text }} text-align: center">{{ value.count_levels }}</p>
                            </td>
                            <td class="{{ value|color_filter_count_order }}">
                                <p style="{{ value|color_filter_count_order_text }} text-align: center">{{ value.count_orders }}</p>
                            </td>
                        {% else %}
                            <td></td>
                            <td></td>
                            <td></td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

app/templates/screener/status_check.html
{% extends "base.html" %}
{% block title %}
    Status
{% endblock title %}
{% block content %}
    
    <h1 style ='text-align:center'>Status</h1>
    <div class="table-responsive">
        <table id="tblStatus"
                class="table mt-2 table-bordered table-striped table-hover table-responsive">
            <thead class="table-dark">
                <tr>
                    <th style='text-align:center'>Name</th>
                    <th style="text-align:center">Status</th>
                    <th style="text-align:center">Date Update</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <script>
        $(document).ready(function(){
            setInterval(function(){
                $.ajax({
                    type: 'GET',
                    url : "/get_data_status",
                    success: function(response) {
                        
                        $('#tblStatus tbody').empty();
    
                        try{
                            var tr;
                            $.each(response.status_list, function (index, status){
                                if (status[2] == 'active')
                                {
                                    tr = $(`<tr class="table-success">`);
                                } 
                                else
                                {
                                    tr = $(`<tr class="table-danger">`);
                                }
                                tr.append(`<td style="text-align:center;">${status[1]}</td>`);
                                tr.append(`<td style="text-align:center;">${status[2]}</td>`);
                                tr.append(`<td style="text-align:center;">${status[3]}</td>`);
                                
                                
                                tr.append(`</tr>`)
                                $('#tblStatus').append(tr); 
                            });


                        }
                        catch(err){
                            console.log(err);
                        }
                    },
                    error : function(response){
                        
                    }
                });
            },3000);
        })
    </script>
{% endblock content %}